language: node_js
node_js:
- '10'
- '12'
cache: yarn
deploy:
  provider: npm
  email: cy.brown59@gmail.com
  api_key:
    secure: Y9is9kxAKiGcwb8lgPj3mOPMLZzQrZQfzldylojyp6+uJixzs0rrJuTQqTt5MGkXfGbN51BQhoYb1Sva+n4VkgQODJZhdBPi23MkJT7z/gI2txzVHFjnwyQ1lWuz5kc/a1BpKKPHnX8lZL8jUn3MBnMHWnn9aV13jZ+ySvQKJExuM8iPEmwSwLrIjq3YXJyX158OPGJd/uESEdGF9CXTL8E9RPRPWREzkKpczE8aL63S8WcsZDGwXwXioLzQBesisFgutB9aswY84VDONn8CqaYUQPhJJmgdo4mjOe9jp9kPuNTuzuzq+k2urOF1cu0wz9oL9veEUDK9Li7ctX+5hZlGzJToB41rb7rO45f4GBySkAUxEKMTZ6ChAAoFLifnfnL6cC1O8N5BXIB8nxNSWT1KWX4oda/VJ7nVu7hN52HkdWRBOxrnXzRa4uDdJVxiZKH/37ElDQSIGzc6Q3096/BFDq0OfrGzcufJ7MmWNjXGU8AvHTvWaMu20K8YJVw3uAZhDO+7paqNYdcFcDOeU2beLggVYFDSClYFUenWSn2nfcOMR+d+OYAkuin2tBCsm/DPpCenk8Ga8za1C2W+N1xhl3nTFJ3U51mpvu6ER//h7/pkPa8fGvnPv8gleYTVbhD/OsRbpWlqWqyEnUjoTKlgBonHKbM2noaSw6RChcw=
  on:
    tags: true
    node: '12'
