language: node_js
node_js:
- '4.0'
- '5.0'
- '6.3'
- '7.0'
deploy:
  provider: npm
  email: cy.brown59@gmail.com
  api_key:
    secure: JbhCB57tqaXWUpNk4CnCzP1ejW6eN7rOrMUqhpiLnnImjNPqknMiRrv/A9DbLDb/1W0wl1lv3WQ/GygKmzQFyU7oTfy+kuEftwkQ28hI2K72ky0Rg41FAydX+zYqjE0AdurfEbsM78XbH6RPTh4ZjYJH/Db8PBhWUZTNN4EeLMYi5YkLiDg3zjp13l9nZ7yNFPBb/qxyc/q3bcmAi4pMmmeyOzfLtEJPHow2RNZTZ8yCA/cRkqn89yBHYoOOnxo9zraPBnydMRSJW349VRyUuROSPLIB1Aa6Waa4kot3WnZTYpaj6UuTPLlS5XNmItSwqKCjRKXkJksUY2Ne1COze6hwGVI8HjN+fRMGoe2P3bClJozLhvSnHc7Fbjivz88z9VQ3iG5RJ0contttsoC/gksv1m3kr7oRZn3YL0NrmfnZ2zrKmFN4bfMtlZcFhbjhdsXhtGdUcd0dX5wzfEr6++b6Ur1AyhDH8Z7piYq1ZqahKoVXEAAQeL+jgb5bQairsr9tV4i6NvnB6ciFN/J7S4owGu0g6Cy/fc+ljy5GAZyCWZHhj5cXicLchYTjipicKgb8hfnjUzYl4huVQ8nm+76TC3WDpjcA5zkIz5AI61Lyl+V49rwsyNcJ4C9LMHTqqyp8ilbsanVOR+p2klkvjjf4J3VkcctOjWQsnJw8j54=
  on:
    tags: true
    branch: master
    node: '7.0'