language: node_js
node_js:
- '8'
- '9'
- '10'
- '11'
cache: yarn
deploy:
  provider: npm
  email: cy.brown59@gmail.com
  api_key:
    secure: QpOjO5YypiwUXGx/ifs/HVMlFb2OoOlozqcK7/lllvmI3hDEYQyZ1ZnL2jhe2cwyJDsFAre9w2gLksNAjtvn+ifd+Z1r4xSmvyUTjiKk30r0KMxATnr3LMdTwHSGbdMyFHJ6pE5GNw2LEKxOuHS9OAZrQjBHdXTh19jSw6cpKmu8608XLRh7FRDyJbVHMYfuyBh/S5EKfmFicHhYVwxOYT651oDyoRQC3Tn34UxY1wEPNQycZ3ZbDuVrCp1e75avBHV/T+pzVFklVzatfkrXWlskC0aJK9dFszvxGZpJS/PwhY8VFeRucrZeCoslKZeyAUHLYZXaHMiRL7FCPTI7jwF5k7QO9Ob/LDhaIKPXtJy461pR9HzzUYgqcJN7FGM8NgIPENtNYKL+4tmd/ufV965K3dx2xIkd2Blh3fH4ORz2prCi/N04qPHTHcdGRSV7EpXoEK7ied6Wn0d7skFBLnY9k/6vjR7k1kmkFeoAxMeI6keCKkaXUikn3h47y586omhF8xJCfN1o+AKu/u8/5weQrezaOsNu1zPVmgiTok3ZHkh2MvxW++kfaqw6yqnpIZ2eOwUGwjYM9MjiKeNSb8ZIOU58pbmO4r0A8JsU7sypAf2LtmssGBNd3NNlM+5PYTVANrWCahpNQowQce+JxFFA7gnnN0hcOdJJG7emRME=
  on:
    tags: true
    branch: master
    node: '8'
